### ISSUE TITLE
Could you update version of `base` dependency?

### ISSUE THREAD

**Issue by paluh** [fizruk/bindings-lxc#2]
I'm trying to install your libraries (`lxc` and `bindings-lxc`) against latest stack LTS-4.2.0. In this release of LTS, there is version 4.2.8.0 of `base`, so I'm not able to install your libraries. Could you update `base` dependency (to: base >=4.7   &&  <=4.8.2.0) in lxc.cabal and in bindings-lxc.cabal?

**Comment by fizruk** [comment]
I have released [`bindings-lxc-0.2.1`](http://hackage.haskell.org/package/bindings-lxc-0.2.1) and [`lxc-0.3.2`](http://hackage.haskell.org/package/lxc) with relaxed upper bounds for `base`.

Those do build on my machine, but something went wrong on Travis.
Unfortunately, Travis has some temporary issues with logs not being displayed.
I will look at it and fix later, when Travis displays logs again.

Please, let me know whether those updates work for you!

**Comment by paluh** [comment]
Now it compiles "like a charm" ;-) Thanks a lot for this update and for your work on these libraries!

**Comment by fizruk** [comment]
@paluh I've just looked through the logs and the problem seems to be only the installation of `lxc-dev`.
I haven't been using LXC for a while, so I am not sure what's the preferred way to install changed to.

If you have an idea of how to fix the builds, that would be very nice!
